// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

export const firebaseConfig = {
  "projectId": "[[FIRESTORE_PROJECT_ID]]",
  "appId": "[[FIREBASE_APP_ID]]",
  "apiKey": "[[FIREBASE_API_KEY]]",
  "authDomain": "[[FIREBASE_AUTH_DOMAIN]]",
  "measurementId": "[[FIREBASE_MEASUREMENT_ID]]",
  "messagingSenderId": "[[FIREBASE_MESSAGING_SENDER_ID]]"
};
